version: '3.8'

services:
  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - 8000:8000
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      
  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379

volumes:
  postgres_data: