"""Add RBAC system with UserRole and OrganizationMember

Revision ID: 9463a4fd2839
Revises: d114b0c76f65
Create Date: 2025-08-20 20:06:25.739810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9463a4fd2839"
down_revision: Union[str, None] = "d114b0c76f65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "organization", sa.Column("created_by_user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "organization", "user", ["created_by_user_id"], ["id"])
    op.add_column(
        "user", sa.Column("password_must_change", sa.Boolean(), nullable=False)
    )
    op.add_column("user", sa.Column("temp_password", sa.String(), nullable=True))
    op.drop_constraint(op.f("user_organization_id_fkey"), "user", type_="foreignkey")
    op.drop_column("user", "role")
    op.drop_column("user", "organization_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("user_organization_id_fkey"),
        "user",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.drop_column("user", "temp_password")
    op.drop_column("user", "password_must_change")
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_column("organization", "created_by_user_id")
    op.drop_table("organization_member")
    # ### end Alembic commands ###
