"""Add categories

Revision ID: dc3b23dde860
Revises: 9463a4fd2839
Create Date: 2025-08-20 21:50:17.387868

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc3b23dde860"
down_revision: Union[str, None] = "9463a4fd2839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "study", sa.Column("categories", postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study", "categories")
    # ### end Alembic commands ###
